### ISSUE TITLE
calib-* review

### ISSUE THREAD

**Issue by vlstill** [kmzbrnoI/automatic-calibration#30]
`calib-step.h`

* [ ] I don't think that ["diffusion"](https://www.macmillandictionary.com/dictionary/american/diffusion) is the right word for instability in speed
* [x] names starting with an userscore followed by an uppercase letter (or another underscore) are reserved for library implementation and must not be used in user code; it does not matter if they are local/static or constexpr (one of the reason is to allow the library to safely use macro names starting with these characters)
* [x] what is `OSC` (as in `_OSC_MAX_COUNT`)?
* [x] some of the names of private functions/slots are unclear

`calib-step.cpp`

* [x] line 82: constructor cast might be more readable (but this is also OK), but definitely needs spaces around `-`
* [x] I guess the two disconnects are the same in both occurrences, maybe factor them out? Maybe even put the connects to a function for symmetry (but that might make orientation in control flow harder :-/)
* [x] please use spaces around operator `-` (l 62); it is seriously unreadable without it (and you use spaces around other operators, so it is also inconsistent)
* [ ] "manually" increasing step when is too small should also be in a separate function (which, if well named, would also eliminate the need for the comment)
* [x] the end of `wsm_lt_read` seems the same as the end of `calibrate`…
* [x] what is the reason to work with even and odd indices separately in `is_oscilating`?

…

**Comment by vlstill** [comment]
`calib-overview.h`

- [ ] I noticed rather weird namespaces, first, they are extremely short (and therefore the meaning is not obvious) and second they contain basically just a one class, maybe it makes sense, but I consider it a bit wierd
- [x] also, connected to namespaces, `Co::CoError` is not a nice name (`Co::Error` maybe?)
- [x] what is `sp` (as in `_DEFAULT_SP_TIMEOUT`, `sp_adapt_timeout`)
- [x] why is min speed set by attribute while max speed by a constructor?

`calib-overview.cpp`

- [x] _POWER_TRY should not be a vector, you never need it to be dynamically allocated, an `std::array`, a C-style array, or an initializer list (`const auto … = …`) would suffice and both would work in a range for and they could be `constexpr` (therefore the compiler is likely to produce linear code instead of the cycle)
- [ ] would it be possible to extract the common measuring and waiting patterns used in `CalibStep` and `CalibOverview` to a common base?

**Comment by vlstill** [comment]
`power-map`

- [x] I can live with using `std::unique_ptr` instead of optional for return values (although it is not very nice), but an array of `unique_ptr`s is not a nice thing if the only reason `unique_ptr`s are used is that some records can be missing.
- maybe use a special value (negative?) to signify an empty place, or use an array of tuples with bool or one array for floats and one for bools, all of these are better than the array of `unique_ptr`s and you can still keep the interface
- [x] also, here I would not use C-style array, maybe `std::array`?

`speed-map`

- [x] inconsistently placed private members (at the beginning in `speed-map` at the end in `power-map`
- [x] the `unique_ptr`s again
- [x] I have just noticed the use of reserved names in guard macros, even here it is not a good idea
- [x] what is the point of converting file name to `latin1`? most OSes now default to UTF-8 and at least Linux will happily use it in file names
- [x] when using `stoul` and similar, you should handle exceptions, also, invalid CSV should be handled gracefully
- [x] invalid (out of range) steps should probably be warned about, not ignored silently when loading CSV
- [x] `at`: the second line is just a complicated way of saying `return nullptr`
- [x] `setMaxSpeed`: why two loops?

[… all for today]

**Comment by malinajan** [comment]
@vlstill 
> `calib-step.h`: some of the names of private functions/slots are unclear

Could you be more specific? I don't see it.

> `calib-step.cpp`:  line 82: constructor cast might be more readable (but this is also OK), but definitely needs spaces around `-`

Could you give me an example? I don't know what you mean by *constructor cast*.

> `speed-map.h`: I have just noticed the use of reserved names in guard macros, even here it is not a good idea

You mean `_CONST_NAME` or anything else?

**Comment by malinajan** [comment]
> inconsistently placed private members (at the beginning in speed-map at the end in power-map

Would you reccomend me any option? Is there any meaningful argumemnt for the one or the other?

**Comment by vlstill** [comment]
- Names: for example t_sp_adapt,  xn_pom_ok, wsm_ls_*
- int(too) is a constructor cast of foo to int. It is called constructor cast as it looks like constructor invocation (and is so for nontrivial data) the disadvantage is it can to reinterpret casting silently
- #ifndef _SPEED_MAP_H_ (this is guard macro)
- as for placing member, I usually place them at the end to make public interface be first. However, if there are any (private) types these must appear before use, so placing them at the beginning (or even interleaving public and private) might be necessary. I don't know out any real conventions. So just be consistent as far as possible.
